#!/bin/bash
GREEN='\033[1;32m'
RESET='\e[0m'
BLUE='\033[1;34m'
YEL='\033[1;33m'
wget https://raw.githubusercontent.com/sarifadim/sifu/main/token.txt  > /dev/null 2>&1
sleep 1
TIK=$(shuf -n 1 token.txt)
USER=$1
sleep 1
rm -rf ngrok  ngrok-v3-stable-linux-amd64.tgz > /dev/null 2>&1
echo -e "${BLUE} Download ngrok.... ${RESET}"
wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz > /dev/null 2>&1
tar -xvf ngrok-v3-stable-linux-amd64.tgz  > /dev/null 2>&1
./ngrok authtoken $TIK
nohup ./ngrok tcp 9050 --region ap &>/dev/null &
echo -e "${BLUE} Download Proxy.... ${RESET}"
wget https://raw.githubusercontent.com/sarifadim/sifu/main/sokpy.py  > /dev/null 2>&1
sleep 1
nohup python3 sokpy.py &>/dev/null &
echo -e "${BLUE} PROXY ADDRESS: ${RESET}"
echo
echo -e "${YEL} "
curl --silent --show-error http://127.0.0.1:4040/api/tunnels | sed -nE 's/.*public_url":"tcp:..([^"]*).*/\1/p'
echo -e "${RESET}"
echo
echo -e "${BLUE} YOUR IP ADDRESS: ${RESET}"
echo -e "${YEL} "
curl ifconfig.me
echo -e "${RESET}"
echo
